### ISSUE TITLE
Don't work if like is set to <= 100

### ISSUE THREAD

**Issue by emilianodelau** [social-manager-tools/socialmanagertools-gui#39]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.5.6
- **Operating System:** Mac OS 10.14.1 Beta (18B57c)

### Expected Behavior

Receive some feedback that the app is running.

```

```

### Actual Behavior

The app freezes and nothing happens. I installed Social Manager Tools. Am I also supposed to install separate .js packages for each social media?
```

```

### Steps to Reproduce

Run social manager tools. 
Select  Instagram bot
Enter account and password
Enter 100 likes a day

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by emilianodelau** [comment]
Patrick,

I am trying Twitter now. Set to 200 likes/day, and it is working. 

I’ll try Instagram now.







Emiliano De Laurentiis
Founder & CEO

Knowledge Avatar <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/cc48292f-07e9-4023-98f9-f0da5de8c65e>s Inc <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/5754fd8c-780c-4f12-82a5-3a3b7be44dac>.
Teach and Learn Intelligently™

‭413.300.1198
Twitter: @emilianodelau <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/acf446e7-f81a-4137-a135-0cc5cb5d2461>
LinkedIn: emilianodelaurentiis <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/bf4e28d8-7980-48ea-b0f7-1f5d93a2a7f2>

Click here to schedule an appointment. <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/94de0160-44ed-437f-9f09-18d0b431198a>


Twitter: @knowledgeavatar <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/0d4e6f04-4f39-4061-b4b8-3f0922459dfa>

**Comment by ptkdev** [comment]
Imho bug is on 100 like/day. If you set 100 on `realistic mode` bot don't work. 

Try more than 100. I try check today why with 100 don't work.

**Comment by emilianodelau** [comment]
At 200 likes logs indicated that it was working. 

By the way, I’d be happy to help you with English translations.







Emiliano De Laurentiis
Founder & CEO

Knowledge Avatar <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/ecefc71b-dbb1-4802-909a-21735dbb91ab>s Inc <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/db47e3c9-c4b9-423f-ad66-89c3e6feedb4>.
Teach and Learn Intelligently™

‭413.300.1198
Twitter: @emilianodelau <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/e639141a-999d-4b09-9c5a-ff1f207d6282>
LinkedIn: emilianodelaurentiis <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/debf4950-1d54-4c58-89ab-3025af870f89>

Click here to schedule an appointment. <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/36f60aa4-48ba-4a2a-993a-32ec2149497c>


Twitter: @knowledgeavatar <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/6a2c3a16-f9eb-4db2-af27-65c5f30516a6>

**Comment by ptkdev** [comment]
Send me pull request if you want correct grammar ✌️

**Comment by emilianodelau** [comment]
Grammar is not too bad - but could use some help. I will send pull request. Which country are you in?

I see that I cannot run two social media at the same time. When I switch from Twitter to IG, Twitter goes off. I’m sure you know that.  Also I predict that people will want to run multiple Twitter or IG accounts at the same time.







Emiliano De Laurentiis
Founder & CEO

Knowledge Avatar <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/d806fe35-210e-4602-96c8-87e943dccce0>s Inc <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/c66d90ba-01e9-48a5-8029-2f4b3d7b6e7e>.
Teach and Learn Intelligently™

‭413.300.1198
Twitter: @emilianodelau <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/4bbb3fda-c18b-4edc-9f2a-201fe883655b>
LinkedIn: emilianodelaurentiis <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/7c3c7fc4-f30a-4f6a-8159-dbbb215c4b0f>

Click here to schedule an appointment. <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/66ad7f30-355a-4486-b9ed-fb62e3620d3c>


Twitter: @knowledgeavatar <https://beta.mailbutler.io/tracking/hit/b260f99e-be59-4921-bbea-3972f69ca2f6/3cfbef0e-fff5-4503-86b1-f21380c3161e>

**Comment by ptkdev** [comment]
Italy.

You can start 2 different social and 2 different mode on same account. Twitter like 12 account and stop X minutes. Idem instagram.

If you write again your nickname and click logs bot is running :) it's just an impression that has stopped

**Comment by ptkdev** [comment]
200 like/day (24h) is less than 9 like/hours. Bot sleep 50 minutes before next session of likes.

**Comment by emilianodelau** [comment]
Aha.

By the way, I am Italian. 

Emiliano

**Comment by emilianodelau** [comment]
I am new to GitHub. My understanding is that either I have to be given permission to be a collaborator or you need to create a new branch in order to  start a pull request.

**Comment by ptkdev** [comment]
@emilianodelau you need fork this project and send pull request

**Comment by ptkdev** [comment]
Fixed in **v0.6.5**
