### ISSUE TITLE
Bot not start if password contains special char (apos/double apos)

### ISSUE THREAD

**Issue by hooshyar** [social-manager-tools/socialmanagertools-gui#54]
### Versions

- **Social Manager Tools Version:** v0.6.2
- **Social Platform:** Instagram
- **Operating System:** Windows 10

### Expected Behavior

Lunch Instagram bot and start doing its job

### Actual Behavior

Nothing, just Loading,

### Steps to Reproduce

1. Download it on Windows 10
2. Run as admin or not
3. Add account then try every mode possible
4. Nope, not showing the "bot started working"
5. I think the problem is with writing data in windows the app has no problem in Mac.
also great work buddy!
### config.js (remember to remove password)

stable version; not using the code

### Screenshots (Optional)
![social_manager_tools](https://user-images.githubusercontent.com/1933643/49275261-0324a000-f490-11e8-8587-1f55478de963.jpg)

**Comment by ptkdev** [comment]
@hooshyar If you set "debug mode" to "enabled" google chrome run on instagram page and bot insert automatically user/pass?

**Comment by hooshyar** [comment]
> @hooshyar question: If you set "debug mode" to "enabled" google chrome run on the Instagram page and bot insert automatically user/pass?

No, not lunching chrome, when I start the app, it creates two folders in Roaming, one Roaming/Social Manager Tools    and another Roaming/social-manager-tools 
I've removed both folders, but when I lunch the app, it generates both again.

**Comment by hooshyar** [comment]
this account password contains: '$"^% like chars.
maybe that causes the problem?

**Comment by ptkdev** [comment]
@hooshyar thanks, this is important bug for me. Password is saved (locally) in `C:/Users/[nickname]/AppData/Roaming/social-manager-tools/[nickname]_config.json` file. Imho special character corrupt json syntax. I fix this in next release: yes problem is with apos / double apos.

**Comment by hooshyar** [comment]
love ya, buddy. great work you do.

**Comment by ptkdev** [comment]
Available in **0.6.5** (coming soon)
