### ISSUE TITLE
Comments issue on instagram

### ISSUE THREAD

**Issue by UN5T48L3** [social-manager-tools/socialmanagertools-gui#56]
### Versions

Replace the values below with your own:

- **Social Manager Tools Version:** v0.6.2
- **Social Platform:** Instagram
- **Operating System:** OSX

I set 200 comments for each day but its going to sleep for 80-100 minutes after only one comment.
so It will comment avarage 18 comments each day.
Am I wrong?

### Screenshot
![ekran resmi 2018-12-23 22 25 01](https://user-images.githubusercontent.com/39417235/50386923-75d91200-0702-11e9-854f-c8e3b91940d2.png)

**Comment by ptkdev** [comment]
Bot write 12 comments and after go sleep ~80 minutes. After 24 hours leave ~200 comments the math is not at opinion

**Comment by UN5T48L3** [comment]
> Bot write 12 comments and after go sleep ~80 minutes. After 24 hours leave ~200 comments the math is not at opinion

When I set enable the debug mode It shows only 1 picture commented. Thats why I am asking it.
How do I make sure 12 comments are written?

**Comment by ptkdev** [comment]
I test this, but i remember is 10-12 comments and sleep

**Comment by UN5T48L3** [comment]
> I test this next days, but i remember is 10-12 comments and sleep

I could not figure out what is wrong with codes. All looks good and stable but I guess somethings changed by instagram server-side

**Comment by ptkdev** [comment]
@UN5T48L3 thx for issue, i test this next days.

**Comment by ptkdev** [comment]
Fixed in **v0.6.5**
