### ISSUE TITLE
Bot doesn't start if max like for day is less than 101

### ISSUE THREAD

**Issue by andre10100** [social-manager-tools/socialmanagertools-gui#58]
### Versions

- **Social Manager Tools Version:** v0.9.10
- **Social Platform:** Instagram
- **Operating System:** OSX

### Expected Behavior

I don't know, as it has never worked. I guess it should run or open an other window that says " Hey I'm working".

### Actual Behavior

The bot doesn't start after that I set up all the settings. It loads for ages without any result.

### Personal notes

My password doesn't contain any special character or number :)

**Comment by ptkdev** [comment]
1. Google chrome is installed? Is >= v70? Is mandatory
2. Path of Google chrome exist? Example, if you run in terminal: `open -na /Applications/Google\ Chrome.app/` that work?
3. Please screenshot me page of your configuration

I run app on OSX without any problem

**Comment by andre10100** [comment]
This is the screenshot after that i click on start. The cursor changes into the hand and after that anything happens.
<img width="1440" alt="schermata 2019-02-26 alle 11 07 15" src="https://user-images.githubusercontent.com/48029919/53441386-969c3d00-39bb-11e9-9140-4c240d963547.png">

1.I'm sorry i didn't understand how to do it
2.When I run it from terminal it says: It does not exist

**Comment by ptkdev** [comment]
Ok, problem is in **max like for day = 20**. Mininum is 101. This is bug, i try fixed in next release but is no-sense this value.

If you want 20 like/day it is better to put them yourself, don't need a bot for 20like/day.

**Comment by andre10100** [comment]
ok got it. thanks a lot for your answer. As I have never used a bot before I was trying to use a general number, but what you said it makes completely sense, there is no reasons to use a bot for only 20 likes, I'm definitely going to change the settings. Thanks again!!! 👍

**Comment by ptkdev** [comment]
If work I'm happy ✌️
I add alert in next release, imho is bad freeze if user set less value than 101. Not is user friendly work

**Comment by andre10100** [comment]
it works!!thanks mate! 🥇

**Comment by ptkdev** [comment]
Fixed in **v0.6.5**
