### ISSUE TITLE
on one user it will say chrome is not installed but not another user.

### ISSUE THREAD

**Issue by kikimedia** [social-manager-tools/socialmanagertools-gui#60]
### Versions

Replace the values below with your own:

- **Social Manager Tools Version:** v0.6.4
- **Social Platform:** Instagram
- **Operating System:** mac el cap 10.11.6

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.
on one user it will say chrome is not installed but not another user. I uninstalled chrome and reinstalled it. same with chromium. only does this with one user and not others. 

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
You need fix path manually in the chrome inputbox. This happen if you install chrome/chromium in different path or in linux os: all linux distro install chrome EVER in different path this is hard to check.

**Comment by kikimedia** [comment]
I put in the path but it was still there on the other profiles. I didn’t change any paths. It just erased the path then after testing if reinstalling chrome or chromium it still would not write in the paths even after new downloads and older versions were installed.

On Apr 27, 2019, at 3:38 AM, Patryk Rzucidło <notifications@github.com<mailto:notifications@github.com>> wrote:


You need fix path manually in the chrome inputbox. This happen if you install chrome/chromium in different path or in linux os: all linux distro install chrome EVER in different path this is hard to check.

**Comment by ptkdev** [comment]
@kikimedia 
This happen when you change chrome path and after change nickname.
**Solution**: change FIRST the nickname and password, after set other configs for this account :)
