### ISSUE TITLE
I can only download an old version

### ISSUE THREAD

**Issue by kikimedia** [social-manager-tools/socialmanagertools-gui#61]
### Versions

Replace the values below with your own:

- **Social Manager Tools Version:** v0.6.4
- **Social Platform:** Instagram
- **Operating System:**mac el cap 10.11.6

### Expected Behavior

Please describe the program's expected behavior.
an update link on gui

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.
I can only download an old version from the website. i cant find a download index. no choices easily found.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Hi! @kikimedia 
This is normal, latest version of app (gui) now is **v0.6.4** but latest CLI is **v0.9.16**

Social Manager Tools app use the CLI utility, but if CLI has a bug i release only cli new release and if this fix is useless for app i not update the app (gui).
