### ISSUE TITLE
DeFollow not working on Windows GUI

### ISSUE THREAD

**Issue by t0bse** [social-manager-tools/socialmanagertools-gui#70]
Hi,
i got this error all the time in my logs. following works, but no one gets unfollowed

> 2019-06-24 12:57:28 [INFO] defollow user piergianframmarcangelo from photo: https://www.instagram.com/p/BzBWKq1oG-I/
> 2019-06-24 12:57:28 [INFO] go to url for try defollow
> 2019-06-24 12:57:28 [INFO] defollow rotate n: 1
> 2019-06-24 12:57:34 [INFO] try defollow
> 2019-06-24 12:57:34 [INFO] username piergianframmarcangelo
> 2019-06-24 12:57:34 [INFO] button text before click: Follow
> 2019-06-24 12:57:42 [DEBUG] TimeoutError: waiting for selector "div[role="dialog"] div > div:nth-child(3) button:nth-child(1)" failed: timeout 5000ms exceeded
> 2019-06-24 12:57:42 [WARNING] defollow error

![image](https://user-images.githubusercontent.com/45834518/60032903-d17f5a80-96a7-11e9-819f-ccfbd4996214.png)

**Comment by GinoPane** [comment]
@t0bse enable debug mode and see what actually happens. This error is likely to happen when bot actually failed to log in (though it says the opposite)

**Comment by ptkdev** [comment]
This days instagram in europe is  in down, is hard try fix bug's. For example today are hashtags has "no photo". Stay tuned...

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
