### ISSUE TITLE
Bot sleeps when debug enabled and Chrome minified

### ISSUE THREAD

**Issue by GinoPane** [social-manager-tools/socialmanagertools-gui#71]
### Versions

Replace the values below with your own:

- **Social Manager Tools Version:** v0.6.5
- **Social Platform:** Instagram
- **Operating System:** Windows 10 

### Expected Behavior

The bot should work in either debug or normal mode

### Actual Behavior

Bot sleeps when debug mode enabled and browser window minimized:

![image](https://user-images.githubusercontent.com/3897579/60577090-5bee4b00-9d87-11e9-8a96-17c979a912e1.png)

So it slept for 1.5 hours just because the Chrome window was minified

**Comment by ptkdev** [comment]
This days instagram in europe is  in down, is hard try fix bug's. For example today are hashtags has "no photo". Stay tuned...

**Comment by ptkdev** [comment]
**Fixed** in Social Manager Tools v0.6.6 and IGBot Library v0.9.18. 
_Remember_: update and use latest chrome version (v75)

[![](https://img.shields.io/badge/donate-paypal-005EA6.svg)](http://paypal.ptkdev.io) [![](https://img.shields.io/badge/donate-patreon-F87668.svg)](http://patreon.ptkdev.io) [![](https://img.shields.io/badge/donate-opencollective-5DA4F9.svg)](http://opencollective.ptkdev.io) [![](https://img.shields.io/badge/buy%20me-coffee-4B788C.svg)](http://coffee.ptkdev.io) [![](https://img.shields.io/badge/help-support@ptkdev.io-fbbc05.svg)](mailto:support@ptkdev.io)
